### ISSUE TITLE
CPC articles with no arXiv categories

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#161]
https://repo.scoap3.org/search?page=1&size=20&journal=Chinese%20Physics%20C&year=2023--2023&q=-arxiv_eprints.categories:hep*

The  2 articles have no `arxiv_eprints.categories`, but the arxiv category exists. 
Why the arXiv category has not been imported in the repo?

**Comment by ErnestaP** [comment]
Every time we were facing this issue, we were adding missing categories manually. 
This time, I added them manually but also fixed the incorrect code so that we wouldn’t have it in the future.

For developers: title (byte string) and arxiv id (as  unicode string) were added to url
