### ISSUE TITLE
Wrong country attributed to an affiliation

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#166]
It seems that for those articles where there is an author affiliated with Sydney, the country was wrongly attributed: UK instead of Australia. 
I guess it is because of "South Wales". But here the string is "New South Wales".
Is it possible to check why this has happened, and see if something can be done to make sure this doesn't happen again. 

Here is the list, would it be possible to correct the values in the repo? 
[Wrong-UK.xlsx](https://github.com/cern-sis/issues-scoap3/files/11745208/Wrong-UK.xlsx)

**Comment by ErnestaP** [comment]
Hi, Anne!
I updated the current articles manually: I changed the country from UK to Australia.
The articles in the future won't have this problem, the changes are deployed on QA, we can see that it worked as expected :)

A few examples from QA:
https://repo.qa.scoap3.org/records/67146
https://repo.qa.scoap3.org/records/66557

@drjova I believe, we can deploy it on PROD

**Comment by agentilb** [comment]
Thanks!
