### ISSUE TITLE
No license for 10.1093/ptep/ptad068 

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#167]
This article is marked as halted because there is no license information available.
Is it because it was not send by the publisher or because we did not extract it correctly on our side? 
If you can send me the files we have received, I can check this.

**Comment by agentilb** [comment]
I see the information is in this field:
<copyright-statement>&#x00A9; The Author(s) 2023. Published by Oxford University Press on behalf of the
                    Physical Society of Japan. This is an Open Access article distributed under the terms of the
                    Creative Commons Attribution License (<ext-link
                        xlink:href="https://creativecommons.org/licenses/by/4.0/" ext-link-type="uri">
                        https:&#x002F;&#x002F;creativecommons.org&#x002F;licenses&#x002F;by&#x002F;4.0&#x002F;
                    </ext-link>), which permits unrestricted reuse, distribution, and reproduction in any medium,
                    provided the original work is properly cited.</copyright-statement>
                <copyright-year>2023</copyright-year>
Does it mean it is not in the correct field?

**Comment by ErnestaP** [comment]
yes, its _permissions/copyright-statement_, we are taking the value from _permissions/license/license-p/ext-link_

**Comment by drjova** [comment]
@agentilb how would you like to proceed with this? Is it something to consider change in our code base?

**Comment by agentilb** [comment]
No, it was a mistake on their side.
They re-uploaded the file ptad068 on Thursday, but it seems the article is still on halted state. Is it possible to check why? 
Has the file not been corrected?

**Comment by drjova** [comment]
@agentilb is it the same workflow or the new one?

**Comment by agentilb** [comment]
No sure. 
Should we delete the halted workflow before she re-uploads the files?

**Comment by drjova** [comment]
hmm it shouldn't matter, could you please ask her to upload again? We will keep an eye on it.

**Comment by agentilb** [comment]
OUP has re uploaded the files. Could you check?

**Comment by agentilb** [comment]
The article is again in halted status: 
https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=777e832e-1599-11ee-ae74-fef813f11e7d

**Comment by ErnestaP** [comment]
@drjova maybe you triggered the article upload in workflows? The article is no more in halted state, it is accessible in repo
