### ISSUE TITLE
Halted articles because arXiv id not recognised

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#175]
Hi,

We have a bunch of halted articles that are "halted" because the system cannot find the arXiv ID.
Message: "Could not determine arXiv category based on id."
But it seems the arXiv ID is fine: 

Doi: 10.1103/PhysRevD.108.012003 
Doi: 10.1103/PhysRevLett.131.021801 
Doi: 10.1103/PhysRevD.108.015011 
Doi: 10.1103/PhysRevD.108.014006 
Doi: 10.1103/PhysRevD.108.014503 
Doi: 10.1103/PhysRevC.108.014906 
Doi: 10.1140/epjc/s10052-023-11737-y 
Doi: 10.1007/JHEP07(2023)079 
Doi: 10.1007/JHEP07(2023)081 
Doi: 10.1007/JHEP07(2023)082 
Doi: 10.1007/JHEP07(2023)087 

Could you have a look?

Thanks!

Anne

**Comment by ErnestaP** [comment]
These articles are in repo and have arxiv ids and categories:
Doi: 10.1103/PhysRevD.108.012003
Doi: 10.1103/PhysRevLett.131.021801
Doi: 10.1103/PhysRevD.108.015011
Doi: 10.1103/PhysRevD.108.014006
Doi: 10.1103/PhysRevD.108.014503
Doi: 10.1103/PhysRevC.108.014906

These not:
Doi: 10.1140/epjc/s10052-023-11737-y -  arxiv id: 2208.07695v2, [link to workflows](https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=fa9a29c8-2018-11ee-9fd2-9637a7fb5199)
This article can be found on arxiv: https://arxiv.org/abs/2208.07695v2
Doi: 10.1007/JHEP07(2023)079 - arxiv id: 2304.08509, [ link to workflows](https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=fa932858-2018-11ee-9822-ae71a8427b95)
This article can be found on arxiv: https://arxiv.org/abs/2304.08509

Doi: 10.1007/JHEP07(2023)081 - arxiv id: 2305.01736,  [link to workflows](https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=fa8db814-2018-11ee-96d9-9ac547b63b6a)
This article can be found on arxiv: https://arxiv.org/abs/2305.01736

Doi: 10.1007/JHEP07(2023)082 - arxiv id: 2303.10237,  [link to workflows](https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=fa8c6676-2018-11ee-afd1-ae238db3221a)
This article can be found on arxiv: https://arxiv.org/abs/2303.10237

Doi: 10.1007/JHEP07(2023)087 - arxiv id: 2304.03663,  [link to workflows](https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=fa894afe-2018-11ee-ae20-0a745f33dadf)
This article can be found on arxiv: https://arxiv.org/abs/2304.03663


None of these axiv ids are found of arxiv api.
Can it be that these articles are not posted in `https://export.arxiv.org/api`?


For DEVELOPERS:
The API looks like this: https://export.arxiv.org/api/query?search_query=id:VALUE_OF_ARXIV_ID

**Comment by ErnestaP** [comment]
Fixed: The JSON output was missing key "categories". Fix, the article is in the repo: https://repo.scoap3.org/records/80487
