### ISSUE TITLE
Change country for those institutions

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#186]
Hi,

Those affiliations were attributed to Hong-Kong but they should be attributed to China.
Could you please change it in the repository? 
[chinese_institution.xlsx](https://github.com/cern-sis/issues-scoap3/files/12279529/chinese_institution.xlsx)

Thanks!

**Comment by agentilb** [comment]
Edit: I have modified the file, the previous one was not complete.

**Comment by ErnestaP** [comment]
@agentilb  the code changes are tested and deployed on prod, to avoid this problem in the future. Also, the articles, which were already in the repo were fixed manually. Can we close the issue?
