### ISSUE TITLE
Articles missing affiliations

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#211]
Hi,

While checking the country shares, I realised that some articles (Collaboration papers mainly lack the affiliations). 

Would it be possible to re-harverst them?
Or should I ask the publishers: 

Springer: 
10.1007/JHEP01(2023)160
10.1007/JHEP01(2023)055
10.1007/JHEP03(2023)171
10.1007/JHEP06(2023)118
10.1007/JHEP08(2023)121
10.1007/JHEP08(2023)131
10.1007/JHEP08(2023)178
10.1007/JHEP09(2023)146

APS:
10.1103/PhysRevD.106.126001
10.1103/PhysRevD.107.012003
10.1103/PhysRevD.107.012006
10.1103/PhysRevD.107.032001
10.1103/PhysRevD.107.032003
10.1103/PhysRevD.107.032004
10.1103/PhysRevD.107.032005
10.1103/PhysRevD.107.032008
10.1103/PhysRevD.107.032013
10.1103/PhysRevD.107.033003
10.1103/PhysRevD.107.052001
10.1103/PhysRevD.107.052004
10.1103/PhysRevD.107.052009
10.1103/PhysRevD.107.072001
10.1103/PhysRevD.107.072002
10.1103/PhysRevD.107.072008
10.1103/PhysRevD.107.092001
10.1103/PhysRevD.107.092003
10.1103/PhysRevD.107.112009
10.1103/PhysRevD.107.112010
10.1103/PhysRevD.107.112011
10.1103/PhysRevD.107.L031101
10.1103/PhysRevD.107.L031102
10.1103/PhysRevD.107.L031103
10.1103/PhysRevD.107.L051101
10.1103/PhysRevD.107.L091102
10.1103/PhysRevD.108.012002
10.1103/PhysRevD.108.012003
10.1103/PhysRevD.108.012004
10.1103/PhysRevD.108.032006
10.1103/PhysRevD.108.052011
10.1103/PhysRevD.108.L031104
10.1103/PhysRevLett.130.031901
10.1103/PhysRevLett.130.071802
10.1103/PhysRevLett.130.071804
10.1103/PhysRevLett.130.091902
10.1103/PhysRevLett.130.151903
10.1103/PhysRevLett.130.181803
10.1103/PhysRevLett.130.181804
10.1103/PhysRevLett.130.231801
10.1103/PhysRevLett.130.261802
10.1103/PhysRevLett.131.021801
10.1103/PhysRevLett.131.051804
10.1103/PhysRevLett.131.111803
10.1103/PhysRevLett.131.121802

For those, I guess I need to ask the publisher:

IOP: 
10.1088/1674-1137/acc3f4

OUP:
10.1093/ptep/ptac123

Thanks!

Anne

**Comment by agentilb** [comment]
So, it seems that for most of those articles, they are issued by the BELLE or BELLE2 collaboration, and have no affiliation in their author list.

**Comment by ErnestaP** [comment]
@agentilb  can we close this issue?
