### ISSUE TITLE
arXiv eprints categories not retrieved

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#212]
Hi,

It seems there is again an issue with categories not retrieved from arxiv, and therefore, many articles are halted:

Ex.
10.1007/JHEP10(2023)091 
10.1007/JHEP10(2023)094 
10.1007/JHEP10(2023)096 
10.1103/PhysRevLett.131.161801 
10.1103/PhysRevD.108.074509 
10.1103/PhysRevLett.131.161901 
10.1103/PhysRevD.108.086022 
10.1140/epjc/s10052-023-11952-7 
10.1007/JHEP10(2023)082
10.1103/PhysRevD.108.063503 
10.1103/PhysRevLett.131.151602 
10.1103/PhysRevLett.131.151903 
...
is it the same issue as in Inspire? 

Can you please have a look?

Thanks,
Anne

**Comment by agentilb** [comment]
We have still those articles in halted mode because the arXiv ID was not retrieved:
[10.1103/PhysRevLett.131.151602 ](http://doi.org/10.1103/PhysRevLett.131.151602)
[10.1007/JHEP10(2023)088 ](http://doi.org/10.1007/JHEP10(2023)088)
[10.1007/JHEP10(2023)094 ](http://doi.org/10.1007/JHEP10(2023)094)
[10.1007/JHEP10(2023)096 ](http://doi.org/10.1007/JHEP10(2023)096)
[10.1103/PhysRevD.108.086022 ](http://doi.org/10.1103/PhysRevD.108.086022)
[10.1140/epjc/s10052-023-11952-7 ](http://doi.org/10.1140/epjc/s10052-023-11952-7)
[10.1007/JHEP12(2023)100 ](http://doi.org/10.1007/JHEP12(2023)100)
[10.1007/JHEP12(2023)064 ](http://doi.org/10.1007/JHEP12(2023)064)
 [10.1007/JHEP12(2023)062 ](http://doi.org/10.1007/JHEP12(2023)062)
[10.1016/j.physletb.2023.138245 ](http://doi.org/10.1016/j.physletb.2023.138245)
 [10.1103/PhysRevD.108.124041 ](http://doi.org/10.1103/PhysRevD.108.124041)
10.1140/epjc/s10052-023-12324-x

Could you please force it so they are correctly uploaded? 

Thanks!

**Comment by agentilb** [comment]
Hi @ErnestaP ,

There are more articles where the arXiv ID couldn't be retrieved. They arrived yesterday: 

Doi: 10.1103/PhysRevD.108.116015 
Doi: 10.1103/PhysRevD.108.112008 
Doi: 10.1103/PhysRevD.108.112009 
Doi: 10.1103/PhysRevD.108.114019 
Doi: 10.1016/j.physletb.2023.138378 

Would it be possible to force it? Or should I do it manually?

**Comment by ErnestaP** [comment]
Hi Anne! Can you please write down the publishers next to each article and approximate dates when they had to be reharvest, to speed up the process? :)

**Comment by agentilb** [comment]
It is not the article that needs to be reharvested, it is the category that needs to be fetched from arXiv. 
I guess it is still the same issue as we had a few weeks ago. 
Wouldn't it be quicker if I add the category manually?

**Comment by ErnestaP** [comment]
During the reharvest we are updating the article as well, so the axiv ids will be added :) Same as when we reharvest when we want to add the fixed affiliations and etc. Actually, it might be easier to add them manually, since articles are from different publishers

**Comment by agentilb** [comment]
Done!

**Comment by ErnestaP** [comment]
Can we close this issue? :)

**Comment by agentilb** [comment]
I think so.
The problem is on the API retrieving arXiv categories which it seems doesn't always work. But if I understand, this is on arXiv side.

**Comment by ErnestaP** [comment]
yes, it is frustrating
