### ISSUE TITLE
Elsevier: missing affiliations

### ISSUE THREAD

**Issue by ErnestaP** [cern-sis/issues-scoap3#268]
https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=e5fb067c-9ffc-11ee-a28f-de4bf41d5b50
Missing affiliation, a snippet from XML:
```
<ce:author-group id="aut0001">
            <ce:author id="au0001" author-id="S0550321323003383-ca442c29413df15c2422663e3c0e5dfa">
                <ce:given-name>A.</ce:given-name>
                <ce:surname>Zee</ce:surname>
                <ce:e-address type="email" xlink:href="mailto:zee@kitp.ucsb.edu" id="ead0001">
                    zee@kitp.ucsb.edu</ce:e-address>
            </ce:author>
        </ce:author-group>
```
file path: ./CERNAB00000010949/05503213/v998sC/S0550321323003383/main.xml

https://repo.scoap3.org/admin/workflow/details/?url=%2Fadmin%2Fworkflow%2F%3Fflt0_21%3D2&id=e609b848-9ffc-11ee-bc44-e69d0c94482a
Missing affiliation, a snippet from XML:
```
        <ce:author-group id="aut0001">
            <ce:author id="au0001" author-id="S0550321323003395-f729a3eebbb6f551fab53a375093f38c">
                <ce:given-name>Sheldon Lee</ce:given-name>
                <ce:surname>Glashow</ce:surname>
            </ce:author>
        </ce:author-group>
```

file path: ./CERNAB00000010949/05503213/v998sC/S0550321323003395/main.xml

**Comment by ErnestaP** [comment]
[download (2).zip](https://github.com/cern-sis/issues-scoap3/files/13743282/download.2.zip)
@agentilb  original files

Can you please contact Elsevier regarding these affiliations?

**Comment by agentilb** [comment]
It is the same issue, but those 2 articles don't need to be in the repo, they are obituaries. So I have deleted the corresponding workflows.

**Comment by agentilb** [comment]
This issue can be closed
