### ISSUE TITLE
OUP article not in the repo

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#269]
Hi,

Here is an article received on 27/12/2023, which doesn't seem to be in the repo: 
Ptad147

<img width="637" alt="Screenshot 2024-01-08 at 13 22 48" src="https://github.com/cern-sis/issues-scoap3/assets/12181904/73239601-d4c0-4390-826c-d7f62c694536">

**Comment by ErnestaP** [comment]
The article is in the repo :) It was again an issue with arxiv
https://repo.scoap3.org/records/82577
