### ISSUE TITLE
Many halted articles because of arXiv category not retrieved

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#275]
Many articles harvested during the Christmas break are stuck in halted mode because of the arXiv problem. 
Could we try to find a solution?

**Comment by ErnestaP** [comment]
Hi @agentilb ! Unfortunately, this is the problem from arxiv, the only solution is to restart the workflows, in order to request the ids again.

The workflows are restarted, no halted articles regarding arxiv id left :)

**Comment by ErnestaP** [comment]
can we close the issue?
