### ISSUE TITLE
APS articles not in the repo

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#278]
Hi,

It seems more APS articles were not harvested in the repo.
Is it due to the issue with arXiv? 

Could we try to re-harvest them and check why they were not harvested. 

Thanks,

Anne
[APS HEP December 2023 Articles Missing from CERN Repository 01112024.xlsx](https://github.com/cern-sis/issues-scoap3/files/13915818/APS.HEP.December.2023.Articles.Missing.from.CERN.Repository.01112024.xlsx)

**Comment by ErnestaP** [comment]
Nom it cannot be the case, the halted articles were fixed 2 days ago. I will see what can I do :)

**Comment by ErnestaP** [comment]
All of the articles are in the repo now.
I am not sure what happened, the missing articles were from a date range: 2023-12-04 until 2023-12-05
The articles were neither in the Halted state nor in the Error state.
@agentilb  can you please double-check, and let me know if we can close the issues?

**Comment by agentilb** [comment]
Hi Ernesta, everything is fine. You can close the ticket

**Comment by agentilb** [comment]
Thanks :-)
