### ISSUE TITLE
Find all missing files and fix them

### ISSUE THREAD

**Issue by ErnestaP** [cern-sis/issues-scoap3#294]
- [x] Find all paths that are missing (and recirds dois)
- [x] Find from which tar/zip/api it is coming from
- [x] Attach files to the records

**Comment by ErnestaP** [comment]
All missing files: 
[missing_files_glnzd.txt](https://github.com/cern-sis/issues-scoap3/files/14099571/missing_files_glnzd.txt)

**Comment by ErnestaP** [comment]
All files are from Elsevier.
In total 1245

**Comment by ErnestaP** [comment]
[final_missing_paths_dkpvp.txt](https://github.com/cern-sis/issues-scoap3/files/14126602/final_missing_paths_dkpvp.txt)

Missing files paths

**Comment by ErnestaP** [comment]
Paths of missing mapped with dois:
[all_missing_files_locations_and_dois_letww.json](https://github.com/cern-sis/issues-scoap3/files/14127571/all_missing_files_locations_and_dois_letww.json)


The newest files were selected, which means, that if there were 2 XMLs, the newest one was taken

**Comment by ErnestaP** [comment]
I updated the files in production, attached almost all missing XMLs, PDFs and PDFAs. We are missing 194 pdf/a files:
[missing_files1_jsqce.txt](https://github.com/cern-sis/issues-scoap3/files/14162141/missing_files1_jsqce.txt)

**Comment by ErnestaP** [comment]
I was not able to find pdfa's for the following records, neither in prod nor in qa:
[missing_pdfas_dois.txt](https://github.com/cern-sis/issues-scoap3/files/14165461/missing_pdfas_dois.txt)

**Comment by ErnestaP** [comment]
The missing PDFAs were in unextracted zips, in the download folder.
It should not happen, that the record is only present in `/data/harvesting/Elsevier/download` folder, and is registered, but not extracted to `data/harvesting/Elsevier/unpacked` folder

**Comment by pamfilos** [comment]
closing as fixed
