### ISSUE TITLE
Change publication date for those records

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#324]
10.1016/j.physletb.2021.136474
10.1016/j.physletb.2021.136468
10.1016/j.physletb.2021.136466
10.1016/j.physletb.2021.136464
10.1016/j.physletb.2021.136465
10.1016/j.physletb.2021.136463
10.1016/j.physletb.2021.136462
10.1016/j.physletb.2021.136458
10.1016/j.physletb.2021.136454
10.1016/j.physletb.2021.136457
10.1016/j.physletb.2021.136456
10.1016/j.physletb.2021.136455
10.1016/j.physletb.2021.136453
10.1016/j.physletb.2021.136452
10.1016/j.physletb.2021.136449
10.1016/j.physletb.2021.136451
10.1016/j.physletb.2021.136450
10.1016/j.physletb.2021.136443
10.1016/j.physletb.2021.136447
10.1016/j.physletb.2021.136448
10.1016/j.physletb.2021.136446
10.1016/j.physletb.2021.136419
10.1016/j.physletb.2021.136439
10.1016/j.physletb.2021.136444
10.1016/j.physletb.2021.136445
10.1016/j.physletb.2021.136425
10.1016/j.physletb.2021.136440
10.1016/j.physletb.2021.136441
10.1016/j.physletb.2021.136438
10.1016/j.physletb.2021.136442
10.1016/j.physletb.2021.136436
10.1016/j.physletb.2021.136427
10.1016/j.physletb.2021.136437
10.1016/j.physletb.2021.136429
10.1016/j.physletb.2021.136428
10.1016/j.physletb.2021.136420
10.1016/j.physletb.2021.136421
10.1016/j.physletb.2021.136422
10.1016/j.physletb.2021.136426
10.1016/j.physletb.2021.136423
10.1016/j.physletb.2021.136424
10.1016/j.physletb.2021.136418
10.1016/j.physletb.2021.136412
10.1016/j.physletb.2021.136414
10.1016/j.physletb.2021.136417
10.1016/j.physletb.2021.136416
10.1016/j.physletb.2021.136409
10.1016/j.physletb.2021.136411
10.1016/j.physletb.2021.136410
10.1016/j.physletb.2021.136413
10.1016/j.physletb.2021.136415
10.1016/j.physletb.2021.136390
10.1016/j.physletb.2021.136405
10.1016/j.physletb.2021.136378
10.1016/j.physletb.2021.136387
10.1016/j.physletb.2021.136407
10.1016/j.physletb.2021.136403
10.1016/j.physletb.2021.136392
10.1016/j.physletb.2021.136402
10.1016/j.physletb.2021.136404
10.1016/j.physletb.2021.136385
10.1016/j.physletb.2021.136388

They are marked as 2024, but they were published in 2021.
Could you please correct the publication date (taking the creation date)?

Thanks in advance,

Anne

**Comment by ErnestaP** [comment]
@agentilb  please let me know if we can close the issue :)

**Comment by agentilb** [comment]
Yes, you can :-)

**Comment by agentilb** [comment]
Thanks :-)
