### ISSUE TITLE
2 APS articles not in the repo

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#327]
Could you please check why those 2 articles are not in the repo:
10.1103/PhysRevD.109.072003
10.1103/PhysRevD.109.074504
Thanks in advance,

**Comment by ErnestaP** [comment]
Duplicate: https://github.com/cern-sis/issues-scoap3/issues/326

**Comment by ErnestaP** [comment]
@agentilb  articles are in repo

**Comment by ErnestaP** [comment]
@agentilb can we close the issue? :)
