### ISSUE TITLE
Duplicate APS articles in legacy

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#347]
Hi,

Those articles are duplicate in the repo: 
10.1103/PhysRevC.109.054912
10.1103/PhysRevD.109.092010
10.1103/PhysRevD.109.092012
10.1103/PhysRevD.109.093001
10.1103/PhysRevD.109.093004
10.1103/PhysRevD.109.094035
10.1103/PhysRevD.109.094038
10.1103/PhysRevD.109.094039
10.1103/PhysRevD.109.094040
10.1103/PhysRevD.109.094042
10.1103/PhysRevD.109.094043
10.1103/PhysRevD.109.094044
10.1103/PhysRevD.109.094045
10.1103/PhysRevD.109.094512
10.1103/PhysRevD.109.094513
10.1103/PhysRevD.109.094515
10.1103/PhysRevD.109.094517
10.1103/PhysRevD.109.094518
10.1103/PhysRevD.109.095035
10.1103/PhysRevD.109.095036
10.1103/PhysRevD.109.095038
10.1103/PhysRevD.109.095039
10.1103/PhysRevD.109.095041
10.1103/PhysRevD.109.096027
10.1103/PhysRevD.109.096030
10.1103/PhysRevD.109.096031
10.1103/PhysRevD.109.096032
10.1103/PhysRevD.109.096033
10.1103/PhysRevD.109.096034
10.1103/PhysRevD.109.096037
10.1103/PhysRevD.109.103037
10.1103/PhysRevD.109.103537
10.1103/PhysRevD.109.103538
10.1103/PhysRevD.109.105026
10.1103/PhysRevD.109.105027
10.1103/PhysRevD.109.106021
10.1103/PhysRevD.109.L091101
10.1103/PhysRevD.109.L101905
10.1103/PhysRevLett.132.221001
10.1103/PhysRevLett.132.221003
10.1103/PhysRevLett.132.221602
 
Could you please make sure the duplicates are deleted, and see why this has happened? 

Thanks in advance,
Kind regards,

Anne

**Comment by ErnestaP** [comment]
Hi @agentilb! It will not happen again. These articles are duplicated because, around that time in May, we had some issues with data harvesting - two processes (workers) were running to retrieve data. 
It is fixed. 
I will delete the duplications

**Comment by agentilb** [comment]
Perfect, thank you, we can close the issue.
