### ISSUE TITLE
Facet for years doesn't seem to work properly

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#381]
Exemples: 

- When you want to modify the selection of years in the facet, it seems there is a strange behavior: if I want to remove year 2024, it removes also most of 2023. 
- And when we remove oldest years, then most of 2024 records disappear from the result

@pamfilos @Piakret

**Comment by pamfilos** [comment]
done with https://github.com/SCOAP3/scoap3/commit/09dcca64da0917e62f405b34a9137f2828eac26a
