### ISSUE TITLE
Duplicate records in the repo (Elsevier articles)

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#89]
I discovered by chance duplicated records in the repo.
For 2022, I see this list of DOIs with 2 records in the repo:

10.1016/j.physletb.2022.137012
10.1016/j.nuclphysb.2022.115725
10.1016/j.nuclphysb.2022.115726
10.1016/j.nuclphysb.2022.115727
10.1016/j.nuclphysb.2022.115728
10.1016/j.nuclphysb.2022.115731
10.1016/j.nuclphysb.2022.115732
10.1016/j.nuclphysb.2022.115740
10.1016/j.physletb.2022.136908
10.1016/j.physletb.2022.137074
10.1016/j.physletb.2022.137099
10.1016/j.physletb.2022.137105
10.1016/j.physletb.2022.137051
10.1016/j.physletb.2022.137101
10.1016/j.physletb.2022.137138
10.1016/j.physletb.2022.137139

Would it be possible to investigate why this happens?
Is it possible to have 2 identical dois in the repo?

**Comment by ErnestaP** [comment]
@agentilb  can we close the issue?
